//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceClientes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int Id_factura { get; set; }
        public int Id_cliente { get; set; }
        public int Id_mecanico { get; set; }
        public string Estado_mantenimientos { get; set; }
        public int Id_repuestos_utilizados { get; set; }
        public decimal Descuento_sobre_repuestos_utilizados { get; set; }
        public int Id_servicios_realizados { get; set; }
        public decimal Descuento_sobre_servicios_realizados { get; set; }
        public decimal Total_factura { get; set; }
        public System.DateTime Fecha_creacion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Mecanico Mecanico { get; set; }
        public virtual Repuestos_utilizados Repuestos_utilizados { get; set; }
        public virtual Servicios_realizados Servicios_realizados { get; set; }
    }
}
