//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceClientes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repuestos_utilizados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Repuestos_utilizados()
        {
            this.Factura = new HashSet<Factura>();
        }
    
        public int Id_repuestos_utilizados { get; set; }
        public int Id_repuesto { get; set; }
        public int Cantidad_utilizados { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual Repuesto Repuesto { get; set; }
    }
}
